### ISSUE TITLE
Read OAuth client ID from env var somehow, instead.

### ISSUE THREAD

**Issue by preston** [preston/tastyterm#7]
This is a public client ID for OAuth authorization purposes, but the value is currently hardcoded to a development ID, which obviously won't work for others. This value needs to sanely set by a "TASTYTERM_OAUTH_CLIENT_ID" environment variable somehow, because that's how the deploying organization will expect to set it when running the app via the official Docker image.

https://github.com/preston/tastyterm/blob/be9a953c40a86fb2f306b637ef6d913f0774b96a/src/app/views/launch.pug#L10

**Comment by frostbytedata** [comment]
I think we can build this into the Grunt config. It will read the environment variable and replace the string in the file at compile time. If we do decide to switch to Angular CLI, this is built in already using the 'environemnts' config out of the box.

**Comment by preston** [comment]
Sweet!

**Comment by frostbytedata** [comment]
Resolved by: 869fe38c9c13ae842cfe055040be8e4b791f7e79
